stages:
  - lint
  - test

cache:
  key: 
    files:
      - Cargo.lock
  paths:
    - .cargo/
    - target/

clippy:
  stage: lint
  image: rust:latest
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings  # Fail on warnings

rust-stable:
  stage: test
  image: rust:latest
  script:
    - cargo test --features test

rust-1_58:
  stage: test
  image: rust:1.58
  script:
    - cargo test --features test

rust-beta:
  stage: test
  image: instrumentisto/rust:beta
  script:
    - cargo test --features test

rust-nightly:
  stage: test
  image: rustlang/rust:nightly
  allow_failure: true  # Allowed to fail
  script:
    - cargo test --features test
