name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  current-rust:
    name: Tests with Current Rust
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tests
        run: cargo test --features test

  rust-1_58:
    name: Tests with Rust 1.58
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.0
          override: true

      - name: Run tests
        run: cargo test --features test

  rust-beta:
    name: Tests with Rust Beta
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true

      - name: Run tests
        run: cargo test --features test

  rust-nightly:
    name: Tests with Rust Nightly
    runs-on: ubuntu-latest
    continue-on-error: true  # Allowed to fail

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Run tests
        run: cargo test --features test

  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run Clippy
        run: cargo clippy -- -D warnings  # Fail on warnings
